/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import control.*;
import database.*;
import model.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUI_pendaftaran extends javax.swing.JFrame {

    private Koneksi koneksi;
    private controller control;
    private Integer harga;
    
    public GUI_pendaftaran() throws SQLException {
        initComponents();
        harga=0;
        koneksi = new Koneksi();
        control = new controller();
        showCBPendaftar();
        showCBguru();
        showTBLpendaftaran();
    }
    
    public void showCBPendaftar() throws SQLException{
        DefaultComboBoxModel dtp = new DefaultComboBoxModel();
        for(data_pendaftar d : control.getPendaftar()){
            dtp.addElement(d.getNama_pendaftar());
        }
        CBpendaftar.removeAllItems();
        CBpendaftar.setModel(dtp);
    }
    
    public void showCBguru() throws SQLException{
        DefaultComboBoxModel dtg = new DefaultComboBoxModel();
        for(data_guru dg : control.getGuru()){
            dtg.addElement(dg.getNama_guru()+ " (" +dg.getKelas()+ ") "+dg.getJadwal());
        }
        CBguru.removeAllItems();
        CBguru.setModel(dtg);
    }
    
    public void showTBLpendaftaran() throws SQLException{
        DefaultTableModel tblpen = new DefaultTableModel(new String[]{"Nama Pendaftar", "Tgl Daftar", "Harga Khursus"},0);
        for(pendaftaran pend : control.getpendaftaran()){
            tblpen.addRow(new String[]{pend.getData_Pendaftar().getNama_pendaftar().toString(), pend.getTanggal_pendaftar().toString(), pend.getHarga_khursus().toString()});
        }
        TBLpendaftaran.setModel(tblpen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBpendaftar = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        TFtgl = new javax.swing.JTextField();
        BTNdaftar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLpendaftaran = new javax.swing.JTable();
        CBguru = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        BTNdetail = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PENDAFTARAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("KHURSUS BAHASA INGGRIS");

        jLabel3.setText("Nama Pendaftar");

        CBpendaftar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBpendaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBpendaftarActionPerformed(evt);
            }
        });

        jLabel5.setText("Tgl Daftar");

        TFtgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtglActionPerformed(evt);
            }
        });

        BTNdaftar.setText("Daftar");
        BTNdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdaftarActionPerformed(evt);
            }
        });

        TBLpendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBLpendaftaran);

        CBguru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBguruActionPerformed(evt);
            }
        });

        jLabel7.setText("Guru/jadwal");

        BTNdetail.setText("Detail");
        BTNdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdetailActionPerformed(evt);
            }
        });

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNdaftar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFtgl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addComponent(CBpendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CBguru, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNdetail)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBpendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTNdaftar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNdetail)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(748, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFtglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtglActionPerformed

    private void BTNdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdaftarActionPerformed
        pendaftaran pen = new pendaftaran();
        try {
            pen.setData_Pendaftar(control.getPendaftar().get(CBpendaftar.getSelectedIndex()));
            pen.setData_Guru(control.getGuru().get(CBguru.getSelectedIndex()));
            pen.setData_Pendaftar(control.getPendaftar().get(CBpendaftar.getSelectedIndex()));
            pen.setTanggal_pendaftar(new SimpleDateFormat("dd/MM/yyyy").parse(TFtgl.getText()));
            if(control.getPendaftar().get(CBpendaftar.getSelectedIndex()).getKelas_pendaftar().equals("sma")){
                harga = 400000;
            }else if(control.getPendaftar().get(CBpendaftar.getSelectedIndex()).getKelas_pendaftar().equals("smp")){
                harga = 250000;
            }
            pen.setHarga_khursus(harga);
            control.insertPendataran(pen);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(GUI_pendaftaran.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(GUI_pendaftaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNdaftarActionPerformed

    private void CBguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBguruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBguruActionPerformed

    private void BTNdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdetailActionPerformed
        try {
            pendaftaran p = control.getpendaftaran().get(TBLpendaftaran.getSelectedRow());
            String teks = "==============PENDAFTAR================\n" +
                          "Nama Pendaftaran : " +p.getData_Pendaftar().getNama_pendaftar()+ "\n" +
                          "Umur pendaftaran : " +p.getData_Pendaftar().getUmur_pendaftar()+ "\n" +
                          "Kelas            : " +p.getData_Pendaftar().getKelas_pendaftar()+ "\n\n" +
                          "==============DATA GURU=================\n" +
                          "Nama Guru        : " +p.getData_Guru().getNama_guru()+ "\n" +
                          "Alamat Guru      : " +p.getData_Guru().getAlamat_guru()+ "\n" +
                          "Pengajar         : " +p.getData_Guru().getKelas()+ "\n\n" +
                          "==============PENDAFTARAN================\n" +
                          "Tanggal Daftar   : " +p.getTanggal_pendaftar()+ "\n" +
                          "Jadwal Khursus   : " +p.getData_Guru().getJadwal()+ "\n" +
                          "Harga Khursus    : " +p.getHarga_khursus();
            JOptionPane.showMessageDialog(this, teks);
            
        } catch (SQLException ex) {
            Logger.getLogger(GUI_pendaftaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNdetailActionPerformed

    private void CBpendaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpendaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBpendaftarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     new GUI_login().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GUI_pendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNdaftar;
    private javax.swing.JButton BTNdetail;
    private javax.swing.JComboBox CBguru;
    private javax.swing.JComboBox CBpendaftar;
    private javax.swing.JTable TBLpendaftaran;
    private javax.swing.JTextField TFtgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
